using System.Text.Json.Serialization;
using ChatApp.TcpGateway.Core.Messaging;
using ChatApp.TcpGateway.Core.Messaging.Conversations;
using ChatApp.TcpGateway.Core.Messaging.History;
using ChatApp.TcpGateway.Core.Messaging.Sync;
using ChatApp.TcpGateway.Infrastructure.Authentication.Models;

namespace ChatApp.TcpGateway.Infrastructure.Serialization.Json;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(AuthenticationRequest))]
[JsonSerializable(typeof(AuthenticationResponse))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(AttachmentRef))]
[JsonSerializable(typeof(List<AttachmentRef>))]
[JsonSerializable(typeof(AttachmentWireStatus))]
[JsonSerializable(typeof(MessageAcknowledgement))]
[JsonSerializable(typeof(MessageReceiptRequest))]
[JsonSerializable(typeof(MessageReceiptAcknowledgement))]
[JsonSerializable(typeof(MessageReceiptUpdate))]
[JsonSerializable(typeof(MessageHistoryRequest))]
[JsonSerializable(typeof(MessageHistoryResponse))]
[JsonSerializable(typeof(MessageHistoryCursor))]
[JsonSerializable(typeof(MessageHistoryItem))]
[JsonSerializable(typeof(List<MessageHistoryItem>))]
[JsonSerializable(typeof(ConversationListRequest))]
[JsonSerializable(typeof(ConversationListResponse))]
[JsonSerializable(typeof(ConversationListCursor))]
[JsonSerializable(typeof(ConversationListItem))]
[JsonSerializable(typeof(List<ConversationListItem>))]
[JsonSerializable(typeof(ConversationMarkReadRequest))]
[JsonSerializable(typeof(ConversationMarkReadResponse))]
[JsonSerializable(typeof(ConversationSetPrefsRequest))]
[JsonSerializable(typeof(ConversationSetPrefsResponse))]
[JsonSerializable(typeof(CreateGroupRequest))]
[JsonSerializable(typeof(CreateGroupResponse))]
[JsonSerializable(typeof(AddGroupMembersRequest))]
[JsonSerializable(typeof(AddGroupMembersResponse))]
[JsonSerializable(typeof(RemoveGroupMemberRequest))]
[JsonSerializable(typeof(RemoveGroupMemberResponse))]
[JsonSerializable(typeof(LeaveGroupRequest))]
[JsonSerializable(typeof(LeaveGroupResponse))]
[JsonSerializable(typeof(ChangeMemberRoleRequest))]
[JsonSerializable(typeof(ChangeMemberRoleResponse))]
[JsonSerializable(typeof(ListGroupMembersRequest))]
[JsonSerializable(typeof(ListGroupMembersResponse))]
[JsonSerializable(typeof(ConversationMemberItem))]
[JsonSerializable(typeof(List<ConversationMemberItem>))]
[JsonSerializable(typeof(MemberJoinedUpdate))]
[JsonSerializable(typeof(MemberLeftUpdate))]
[JsonSerializable(typeof(MemberRemovedUpdate))]
[JsonSerializable(typeof(RoleChangedUpdate))]
[JsonSerializable(typeof(MessageRecallRequest))]
[JsonSerializable(typeof(MessageRecallAcknowledgement))]
[JsonSerializable(typeof(MessageRecalledUpdate))]
[JsonSerializable(typeof(MessageEditRequest))]
[JsonSerializable(typeof(MessageEditAcknowledgement))]
[JsonSerializable(typeof(MessageEditedUpdate))]
[JsonSerializable(typeof(AddReactionRequest))]
[JsonSerializable(typeof(AddReactionAcknowledgement))]
[JsonSerializable(typeof(ReactionAddedUpdate))]
[JsonSerializable(typeof(RemoveReactionRequest))]
[JsonSerializable(typeof(RemoveReactionAcknowledgement))]
[JsonSerializable(typeof(ReactionRemovedUpdate))]
[JsonSerializable(typeof(MessageReactionSummary))]
[JsonSerializable(typeof(List<MessageReactionSummary>))]
[JsonSerializable(typeof(TypingNotify))]
[JsonSerializable(typeof(TypingUpdate))]
[JsonSerializable(typeof(PresenceQueryRequest))]
[JsonSerializable(typeof(PresenceUnwatchRequest))]
[JsonSerializable(typeof(PresenceSnapshotResponse))]
[JsonSerializable(typeof(PresenceSnapshotItem))]
[JsonSerializable(typeof(List<PresenceSnapshotItem>))]
[JsonSerializable(typeof(PresenceChanged))]
[JsonSerializable(typeof(ConversationChanged))]
[JsonSerializable(typeof(UnreadCountChanged))]
[JsonSerializable(typeof(SyncBootstrapRequest))]
[JsonSerializable(typeof(SyncBootstrapResponse))]
[JsonSerializable(typeof(ConversationSyncWatermark))]
[JsonSerializable(typeof(List<ConversationSyncWatermark>))]
[JsonSerializable(typeof(ConversationHistoryCatchUp))]
[JsonSerializable(typeof(List<ConversationHistoryCatchUp>))]
[JsonSerializable(typeof(SyncCursorResetRequired))]
[JsonSerializable(typeof(List<SyncCursorResetRequired>))]
[JsonSerializable(typeof(SyncCursorResetReason))]
[JsonSerializable(typeof(AccessTokenRecord))]
public partial class GatewayJsonSerializerContext : JsonSerializerContext;
