using System.Text.Json.Serialization;
using ChatApp.TcpGateway.Core.Authentication;
using ChatApp.TcpGateway.Core.Messaging;
using ChatApp.TcpGateway.Core.Messaging.Attachments;
using ChatApp.TcpGateway.Core.Messaging.Conversations;
using ChatApp.TcpGateway.Core.Messaging.History;
using ChatApp.TcpGateway.Core.Messaging.Push;
using ChatApp.TcpGateway.Core.Messaging.Relationships;
using ChatApp.TcpGateway.Core.Messaging.Sync;
using ChatApp.Realtime.Abstractions.Events;
using ChatApp.Realtime.Abstractions.Push;
using ChatApp.TcpGateway.Infrastructure.Authentication.Models;

namespace ChatApp.TcpGateway.Infrastructure.Serialization.Json;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    // 协议 JSON 改为大小写敏感。早检只精确匹配小写 attachmentIds，
    // 大小写不敏感会让其他大小写形式绕过早检后被正式反序列化接受。
    // 明确协议版本：客户端必须使用 camelCase。
    PropertyNameCaseInsensitive = false,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(AuthenticationRequest))]
[JsonSerializable(typeof(AuthenticationResponse))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(AttachmentRef))]
[JsonSerializable(typeof(List<AttachmentRef>))]
[JsonSerializable(typeof(AttachmentWireStatus))]
[JsonSerializable(typeof(MessageAcknowledgement))]
[JsonSerializable(typeof(MessageReceiptRequest))]
[JsonSerializable(typeof(MessageReceiptAcknowledgement))]
[JsonSerializable(typeof(MessageReceiptUpdate))]
[JsonSerializable(typeof(MessageHistoryRequest))]
[JsonSerializable(typeof(MessageHistoryResponse))]
[JsonSerializable(typeof(MessageHistoryCursor))]
[JsonSerializable(typeof(MessageHistoryItem))]
[JsonSerializable(typeof(List<MessageHistoryItem>))]
[JsonSerializable(typeof(MessageHistoryItem[]))]
[JsonSerializable(typeof(ConversationListRequest))]
[JsonSerializable(typeof(ConversationListResponse))]
[JsonSerializable(typeof(ConversationListCursor))]
[JsonSerializable(typeof(ConversationListItem))]
[JsonSerializable(typeof(List<ConversationListItem>))]
[JsonSerializable(typeof(ConversationListItem[]))]
[JsonSerializable(typeof(ConversationMarkReadRequest))]
[JsonSerializable(typeof(ConversationMarkReadResponse))]
[JsonSerializable(typeof(ConversationSetPrefsRequest))]
[JsonSerializable(typeof(ConversationSetPrefsResponse))]
[JsonSerializable(typeof(CreateGroupRequest))]
[JsonSerializable(typeof(CreateGroupResponse))]
[JsonSerializable(typeof(AddGroupMembersRequest))]
[JsonSerializable(typeof(AddGroupMembersResponse))]
[JsonSerializable(typeof(RemoveGroupMemberRequest))]
[JsonSerializable(typeof(RemoveGroupMemberResponse))]
[JsonSerializable(typeof(LeaveGroupRequest))]
[JsonSerializable(typeof(LeaveGroupResponse))]
[JsonSerializable(typeof(ChangeMemberRoleRequest))]
[JsonSerializable(typeof(ChangeMemberRoleResponse))]
[JsonSerializable(typeof(ListGroupMembersRequest))]
[JsonSerializable(typeof(ListGroupMembersResponse))]
[JsonSerializable(typeof(ConversationMemberItem))]
[JsonSerializable(typeof(List<ConversationMemberItem>))]
[JsonSerializable(typeof(MemberJoinedUpdate))]
[JsonSerializable(typeof(MemberLeftUpdate))]
[JsonSerializable(typeof(MemberRemovedUpdate))]
[JsonSerializable(typeof(RoleChangedUpdate))]
[JsonSerializable(typeof(MessageRecallRequest))]
[JsonSerializable(typeof(MessageRecallAcknowledgement))]
[JsonSerializable(typeof(MessageRecalledUpdate))]
[JsonSerializable(typeof(MessageEditRequest))]
[JsonSerializable(typeof(MessageEditAcknowledgement))]
[JsonSerializable(typeof(MessageEditedUpdate))]
[JsonSerializable(typeof(AddReactionRequest))]
[JsonSerializable(typeof(AddReactionAcknowledgement))]
[JsonSerializable(typeof(ReactionAddedUpdate))]
[JsonSerializable(typeof(RemoveReactionRequest))]
[JsonSerializable(typeof(RemoveReactionAcknowledgement))]
[JsonSerializable(typeof(ReactionRemovedUpdate))]
[JsonSerializable(typeof(MessageReactionSummary))]
[JsonSerializable(typeof(List<MessageReactionSummary>))]
[JsonSerializable(typeof(TypingNotify))]
[JsonSerializable(typeof(TypingUpdate))]
[JsonSerializable(typeof(PresenceQueryRequest))]
[JsonSerializable(typeof(PresenceUnwatchRequest))]
[JsonSerializable(typeof(PresenceSnapshotResponse))]
[JsonSerializable(typeof(PresenceSnapshotItem))]
[JsonSerializable(typeof(List<PresenceSnapshotItem>))]
[JsonSerializable(typeof(PresenceChanged))]
[JsonSerializable(typeof(ConversationChanged))]
[JsonSerializable(typeof(UnreadCountChanged))]
[JsonSerializable(typeof(ConversationReadUpdate))]
[JsonSerializable(typeof(SyncBootstrapRequest))]
[JsonSerializable(typeof(SyncBootstrapResponse))]
[JsonSerializable(typeof(ConversationSyncWatermark))]
[JsonSerializable(typeof(List<ConversationSyncWatermark>))]
[JsonSerializable(typeof(ConversationHistoryCatchUp))]
[JsonSerializable(typeof(List<ConversationHistoryCatchUp>))]
[JsonSerializable(typeof(SyncCursorResetRequired))]
[JsonSerializable(typeof(List<SyncCursorResetRequired>))]
[JsonSerializable(typeof(SyncCursorResetReason))]
[JsonSerializable(typeof(AccessTokenRecord))]
[JsonSerializable(typeof(ProtocolErrorFrame))]
[JsonSerializable(typeof(ClientHello))]
[JsonSerializable(typeof(ServerHello))]
[JsonSerializable(typeof(GoAway))]
[JsonSerializable(typeof(ResumeResponse))]
[JsonSerializable(typeof(RelationshipListChangedUpdate))]
[JsonSerializable(typeof(AttachmentLifecycleUpdate))]
[JsonSerializable(typeof(AttachmentFinalizeRequest))]
[JsonSerializable(typeof(AttachmentFinalizeResponse))]
[JsonSerializable(typeof(RelationshipCommandRequest))]
[JsonSerializable(typeof(RelationshipCommandResponse))]
[JsonSerializable(typeof(RelationshipListRequest))]
[JsonSerializable(typeof(RelationshipListResponse))]
[JsonSerializable(typeof(MembersAddedUpdate))]
[JsonSerializable(typeof(ConversationDissolvedUpdate))]
[JsonSerializable(typeof(RelationshipItem))]
[JsonSerializable(typeof(RelationshipItem[]))]
[JsonSerializable(typeof(RealtimeAttachmentLifecyclePayload))]
[JsonSerializable(typeof(RealtimeUserLifecycleChangedPayload))]
[JsonSerializable(typeof(RealtimeDomainNotificationPayload))]
[JsonSerializable(typeof(RegisterPushTokenRequest))]
[JsonSerializable(typeof(RegisterPushTokenResponse))]
[JsonSerializable(typeof(UnregisterPushTokenRequest))]
[JsonSerializable(typeof(UnregisterPushTokenResponse))]
[JsonSerializable(typeof(PushTokenRecord))]
[JsonSerializable(typeof(ResumeContext))]
[JsonSerializable(typeof(ChatApp.Realtime.Abstractions.Conversations.GroupConversationResult), TypeInfoPropertyName = "RealtimeGroupConversationResult")]
[JsonSerializable(typeof(ChatApp.Realtime.Abstractions.Conversations.ConversationMemberItem), TypeInfoPropertyName = "RealtimeConversationMemberItem")]
[JsonSerializable(typeof(ChatApp.Realtime.Abstractions.Conversations.ConversationMemberRole), TypeInfoPropertyName = "RealtimeConversationMemberRole")]
[JsonSerializable(typeof(ChatApp.Realtime.Abstractions.Conversations.ConversationType), TypeInfoPropertyName = "RealtimeConversationType")]
[JsonSerializable(typeof(List<ChatApp.Realtime.Abstractions.Conversations.ConversationMemberItem>), TypeInfoPropertyName = "RealtimeConversationMemberItemList")]
[JsonSerializable(typeof(System.Collections.Generic.IReadOnlyList<ChatApp.Realtime.Abstractions.Conversations.ConversationMemberItem>), TypeInfoPropertyName = "RealtimeConversationMemberItemReadOnlyList")]
public partial class GatewayJsonSerializerContext : JsonSerializerContext;
