using System.Text.Json.Serialization;
using ChatApp.TcpGateway.Core.Authentication;
using ChatApp.TcpGateway.Core.Messaging;
using ChatApp.TcpGateway.Core.Messaging.Attachments;
using ChatApp.TcpGateway.Core.Messaging.Conversations;
using ChatApp.TcpGateway.Core.Messaging.History;
using ChatApp.TcpGateway.Core.Messaging.Push;
using ChatApp.TcpGateway.Core.Messaging.Relationships;
using ChatApp.TcpGateway.Core.Messaging.Sync;
using ChatApp.Realtime.Abstractions.Events;
using ChatApp.Realtime.Abstractions.Push;
using ChatApp.TcpGateway.Infrastructure.Push;

namespace ChatApp.TcpGateway.Infrastructure.Serialization.Json;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    // 协议 JSON 改为大小写敏感。早检只精确匹配小写 attachmentIds，
    // 大小写不敏感会让其他大小写形式绕过早检后被正式反序列化接受。
    // 明确协议版本：客户端必须使用 camelCase。
    PropertyNameCaseInsensitive = false,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(AuthenticationRequest))]
[JsonSerializable(typeof(AuthenticationResponse))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(AttachmentRef))]
[JsonSerializable(typeof(List<AttachmentRef>))]
[JsonSerializable(typeof(AttachmentWireStatus))]
[JsonSerializable(typeof(MessageAcknowledgement))]
[JsonSerializable(typeof(MessageReceiptRequest))]
[JsonSerializable(typeof(MessageReceiptAcknowledgement))]
[JsonSerializable(typeof(MessageReceiptUpdate))]
[JsonSerializable(typeof(MessageHistoryRequest))]
[JsonSerializable(typeof(MessageHistoryResponse))]
[JsonSerializable(typeof(MessageHistoryCursor))]
[JsonSerializable(typeof(MessageHistoryItem))]
[JsonSerializable(typeof(List<MessageHistoryItem>))]
[JsonSerializable(typeof(MessageHistoryItem[]))]
[JsonSerializable(typeof(ConversationListRequest))]
[JsonSerializable(typeof(ConversationListResponse))]
[JsonSerializable(typeof(ConversationListCursor))]
[JsonSerializable(typeof(ConversationListItem))]
[JsonSerializable(typeof(List<ConversationListItem>))]
[JsonSerializable(typeof(ConversationListItem[]))]
[JsonSerializable(typeof(ConversationMarkReadRequest))]
[JsonSerializable(typeof(ConversationMarkReadResponse))]
[JsonSerializable(typeof(ConversationSetPrefsRequest))]
[JsonSerializable(typeof(ConversationSetPrefsResponse))]
[JsonSerializable(typeof(CreateGroupRequest))]
[JsonSerializable(typeof(CreateGroupResponse))]
[JsonSerializable(typeof(AddGroupMembersRequest))]
[JsonSerializable(typeof(AddGroupMembersResponse))]
[JsonSerializable(typeof(RemoveGroupMemberRequest))]
[JsonSerializable(typeof(RemoveGroupMemberResponse))]
[JsonSerializable(typeof(LeaveGroupRequest))]
[JsonSerializable(typeof(LeaveGroupResponse))]
[JsonSerializable(typeof(ChangeMemberRoleRequest))]
[JsonSerializable(typeof(ChangeMemberRoleResponse))]
[JsonSerializable(typeof(ListGroupMembersRequest))]
[JsonSerializable(typeof(ListGroupMembersResponse))]
[JsonSerializable(typeof(MessageReadReceiptQueryRequest))]
[JsonSerializable(typeof(MessageReadReceiptQueryResponse))]
[JsonSerializable(typeof(DissolveGroupRequest))]
[JsonSerializable(typeof(DissolveGroupResponse))]
[JsonSerializable(typeof(MessageReadReceiptItem))]
[JsonSerializable(typeof(List<MessageReadReceiptItem>))]
[JsonSerializable(typeof(ConversationMemberItem))]
[JsonSerializable(typeof(List<ConversationMemberItem>))]
[JsonSerializable(typeof(MemberJoinedUpdate))]
[JsonSerializable(typeof(MemberLeftUpdate))]
[JsonSerializable(typeof(MemberRemovedUpdate))]
[JsonSerializable(typeof(RoleChangedUpdate))]
[JsonSerializable(typeof(MessageRecallRequest))]
[JsonSerializable(typeof(MessageRecallAcknowledgement))]
[JsonSerializable(typeof(MessageRecalledUpdate))]
[JsonSerializable(typeof(MessageEditRequest))]
[JsonSerializable(typeof(MessageEditAcknowledgement))]
[JsonSerializable(typeof(MessageEditedUpdate))]
[JsonSerializable(typeof(AddReactionRequest))]
[JsonSerializable(typeof(AddReactionAcknowledgement))]
[JsonSerializable(typeof(ReactionAddedUpdate))]
[JsonSerializable(typeof(RemoveReactionRequest))]
[JsonSerializable(typeof(RemoveReactionAcknowledgement))]
[JsonSerializable(typeof(ReactionRemovedUpdate))]
[JsonSerializable(typeof(MessageReactionSummary), TypeInfoPropertyName = "RealtimeMessageReactionSummary")]
[JsonSerializable(typeof(List<MessageReactionSummary>), TypeInfoPropertyName = "RealtimeMessageReactionSummaryList")]
[JsonSerializable(typeof(TypingNotify))]
[JsonSerializable(typeof(TypingUpdate))]
[JsonSerializable(typeof(PresenceQueryRequest))]
[JsonSerializable(typeof(PresenceUnwatchRequest))]
[JsonSerializable(typeof(PresenceSnapshotResponse))]
[JsonSerializable(typeof(PresenceSnapshotItem))]
[JsonSerializable(typeof(List<PresenceSnapshotItem>))]
[JsonSerializable(typeof(PresenceChanged))]
[JsonSerializable(typeof(ConversationChanged))]
[JsonSerializable(typeof(UnreadCountChanged))]
[JsonSerializable(typeof(ConversationReadUpdate))]
[JsonSerializable(typeof(SyncBootstrapRequest))]
[JsonSerializable(typeof(SyncBootstrapResponse))]
[JsonSerializable(typeof(ConversationSyncWatermark))]
[JsonSerializable(typeof(List<ConversationSyncWatermark>))]
[JsonSerializable(typeof(ConversationHistoryCatchUp))]
[JsonSerializable(typeof(List<ConversationHistoryCatchUp>))]
[JsonSerializable(typeof(SyncCursorResetRequired))]
[JsonSerializable(typeof(List<SyncCursorResetRequired>))]
[JsonSerializable(typeof(SyncCursorResetReason))]
[JsonSerializable(typeof(RelationshipSyncWatermark), TypeInfoPropertyName = "RealtimeRelationshipSyncWatermark")]
[JsonSerializable(typeof(List<RelationshipSyncWatermark>), TypeInfoPropertyName = "RealtimeRelationshipSyncWatermarkList")]
[JsonSerializable(typeof(RelationshipCatchUp), TypeInfoPropertyName = "RealtimeRelationshipCatchUp")]
[JsonSerializable(typeof(List<RelationshipCatchUp>), TypeInfoPropertyName = "RealtimeRelationshipCatchUpList")]
[JsonSerializable(typeof(RelationshipChangeLogEntry), TypeInfoPropertyName = "RealtimeRelationshipChangeLogEntry")]
[JsonSerializable(typeof(RelationshipChangeLogEntry[]), TypeInfoPropertyName = "RealtimeRelationshipChangeLogEntryArray")]
[JsonSerializable(typeof(IReadOnlyList<RelationshipChangeLogEntry>), TypeInfoPropertyName = "RealtimeRelationshipChangeLogEntryReadOnlyList")]
[JsonSerializable(typeof(ChatApp.Shared.Protocol.Tcp.RelationshipSyncWatermark), TypeInfoPropertyName = "TcpRelationshipSyncWatermark")]
[JsonSerializable(typeof(IReadOnlyList<ChatApp.Shared.Protocol.Tcp.RelationshipSyncWatermark>), TypeInfoPropertyName = "TcpRelationshipSyncWatermarkReadOnlyList")]
[JsonSerializable(typeof(ChatApp.Shared.Protocol.Tcp.RelationshipCatchUp), TypeInfoPropertyName = "TcpRelationshipCatchUp")]
[JsonSerializable(typeof(IReadOnlyList<ChatApp.Shared.Protocol.Tcp.RelationshipCatchUp>), TypeInfoPropertyName = "TcpRelationshipCatchUpReadOnlyList")]
[JsonSerializable(typeof(ChatApp.Shared.Protocol.Tcp.RelationshipChangeLogEntry), TypeInfoPropertyName = "TcpRelationshipChangeLogEntry")]
[JsonSerializable(typeof(IReadOnlyList<ChatApp.Shared.Protocol.Tcp.RelationshipChangeLogEntry>), TypeInfoPropertyName = "TcpRelationshipChangeLogEntryReadOnlyList")]
[JsonSerializable(typeof(RelationshipChangeOperation))]
[JsonSerializable(typeof(ProtocolErrorFrame))]
[JsonSerializable(typeof(ClientHello))]
[JsonSerializable(typeof(ServerHello))]
[JsonSerializable(typeof(GoAway))]
[JsonSerializable(typeof(ResumeResponse))]
[JsonSerializable(typeof(RelationshipListChangedUpdate))]
[JsonSerializable(typeof(AttachmentLifecycleUpdate))]
[JsonSerializable(typeof(AttachmentFinalizeRequest))]
[JsonSerializable(typeof(AttachmentFinalizeResponse))]
[JsonSerializable(typeof(AttachmentDownloadAuthorizeRequest))]
[JsonSerializable(typeof(AttachmentDownloadAuthorizeResponse))]
[JsonSerializable(typeof(RelationshipCommandRequest))]
[JsonSerializable(typeof(RelationshipCommandResponse))]
[JsonSerializable(typeof(RelationshipListRequest))]
[JsonSerializable(typeof(RelationshipListResponse), TypeInfoPropertyName = "RelationshipListResponse")]
[JsonSerializable(typeof(MembersAddedUpdate))]
[JsonSerializable(typeof(ConversationDissolvedUpdate))]
[JsonSerializable(typeof(RelationshipItem), TypeInfoPropertyName = "RelationshipItem")]
[JsonSerializable(typeof(RelationshipItem[]), TypeInfoPropertyName = "RelationshipItemArray")]
[JsonSerializable(typeof(RealtimeAttachmentLifecyclePayload))]
[JsonSerializable(typeof(RealtimeUserLifecycleChangedPayload))]
[JsonSerializable(typeof(RealtimeDomainNotificationPayload))]
[JsonSerializable(typeof(RegisterPushTokenRequest))]
[JsonSerializable(typeof(RegisterPushTokenResponse))]
[JsonSerializable(typeof(UnregisterPushTokenRequest))]
[JsonSerializable(typeof(UnregisterPushTokenResponse))]
[JsonSerializable(typeof(PushTokenRecord))]
[JsonSerializable(typeof(PushDlqEntry))]
[JsonSerializable(typeof(PushDlqFailedToken))]
[JsonSerializable(typeof(PushDlqFailedToken[]))]
[JsonSerializable(typeof(ResumeContext))]
[JsonSerializable(typeof(ChatApp.Realtime.Abstractions.Conversations.GroupConversationResult), TypeInfoPropertyName = "RealtimeGroupConversationResult")]
public partial class GatewayJsonSerializerContext : JsonSerializerContext;
