<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ChatApp.ResumeVerification</AssemblyName>
    <RootNamespace>ChatApp.ResumeVerification</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ChatApp.Auth.Contracts" />
    <PackageReference Include="ChatApp.Protocol.Tcp" />
    <ProjectReference Include="..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
</Project>
